USE master
GO
IF DB_ID('QLDH') IS NOT NULL
	DROP DATABASE QLDH
GO
CREATE DATABASE QLDH
GO
USE QLDH
GO

--TẠO BẢNG VÀ RÀNG BUỘC KHÓA CHÍNH
CREATE TABLE CongViec
(
	MaCViec INT NOT NULL IDENTITY,
	TenCViec NVARCHAR(50)
	
	CONSTRAINT PK_CongViec 
	PRIMARY KEY(MaCViec)
)
CREATE TABLE LichSuThuong
(
	MaLSThuong INT NOT NULL IDENTITY,
	TienThuong INT,
	NgayThuong DATE,
	MaNV INT,
	LyDo NVARCHAR(500)
	
	CONSTRAINT PK_LichSuThuong PRIMARY KEY(MaLSThuong)
)
CREATE TABLE NV_TTinKhac
(
	MaNV INT NOT NULL IDENTITY,
	CMND_NV CHAR(12),
	SDT_NV CHAR(10),
	NgaySinhNV DATE,
	DiaChiNV NVARCHAR(250)
	
	CONSTRAINT PK_NV_TTinKhac PRIMARY KEY(MaNV)
)
CREATE TABLE LichSuLuong
(
	MaLSLuong INT NOT NULL IDENTITY,
	MaNV INT,
	NgayBD DATE,
	Luong INT
	
	CONSTRAINT PK_LichSuLuong
	PRIMARY KEY(MaLSLuong)
)
CREATE TABLE YeuCauHoTro
(
	MaYC INT NOT NULL IDENTITY,
	MaKH INT,
	Noidung NVARCHAR(MAX),
	TrangThaiYCau TINYINT
	
	CONSTRAINT PK_YeuCauHoTro
	PRIMARY KEY(MaYC)
)
CREATE TABLE NVQuanLy
(
	MaNV INT NOT NULL IDENTITY,
	MatKhauQL VARCHAR(20)
	
	CONSTRAINT PK_NVQuanLy
	PRIMARY KEY(MaNV)
)
CREATE TABLE NhanVien
(
	MaNV INT NOT NULL IDENTITY,
	HoTenNV NVARCHAR(50),
	LuongHienTai INT,
	TrangThaiHD BIT,
	TenCViec NVARCHAR(50),
	MaCViec INT,
	MaCNhanh INT
	
	CONSTRAINT PK_NhanVien
	PRIMARY KEY(MaNV)
)
CREATE TABLE GiaoHang
(
	MaDH INT NOT NULL IDENTITY,
	MaNV INT,
	NgayGiao DATETIME
	
	CONSTRAINT PK_GiaoHang
	PRIMARY KEY(MaDH)
)
CREATE TABLE BanHang
(
	MaDH INT NOT NULL IDENTITY,
	MaNV INT,
	
	CONSTRAINT PK_BanHang
	PRIMARY KEY(MaDH)
)
CREATE TABLE KhachHang
(
	MaKH INT NOT NULL IDENTITY,
	HoKH NVARCHAR(30),
	TenKH NVARCHAR(30),
	SDT_KH VARCHAR(15),
	EmailKH VARCHAR(30),
	MatKhauKH VARCHAR(20),
	DiaChiKH NVARCHAR(250)
	
	CONSTRAINT PK_KhachHang
	PRIMARY KEY(MaKH)
)
CREATE TABLE ChiNhanh
(
	MaCNhanh INT NOT NULL IDENTITY,
	TenCNhanh NVARCHAR(50),
	DiaChiCNhanh NVARCHAR(250),
	SDT_CNhanh CHAR(15),
	PasswordBH VARCHAR(20),
	TrangThaiHD BIT,
	MaTinh TINYINT
	
	CONSTRAINT PK_ChiNhanh
	PRIMARY KEY(MaCNhanh)
)
CREATE TABLE KhuVuc
(
	MaKV INT NOT NULL IDENTITY,
	MaTinh TINYINT,
	Quan_Huyen NVARCHAR(30),
	PhiGiaoHang INT,
	MaCNhanh INT
	
	CONSTRAINT PK_KhuVuc
	PRIMARY KEY(MaKV)
)
CREATE TABLE DonHang
(
	MaDH INT NOT NULL IDENTITY,
	SDT_NgNhan CHAR(10),
	NgayLap DATETIME,
	HinhThucTT TINYINT,
	TrangThaiDH TINYINT,
	TongTienSP INT,
	PhiGiaoHang INT,
	TongTienDH INT,
	MaKH INT,
	MaQTang INT,
	MaCNhanh INT,
	MaKV INT
	
	CONSTRAINT PK_DonHang
	PRIMARY KEY(MaDH)
)
CREATE TABLE DH_TTinKhac
(
	MaDH INT NOT NULL IDENTITY,
	Email_NgGui VARCHAR(30),
	DiaChi_NgGui NVARCHAR(250),
	SDT_NgGui CHAR(10),
	
	CONSTRAINT PK_DH_TTinKhac
	PRIMARY KEY(MaDH)
)
CREATE TABLE DonNhap
(
	MaDNhap INT NOT NULL IDENTITY,
	TongTienNhap INT,
	NgayNhanHang DATE,
	MaNCC INT,
	MaCNhanh INT
	
	CONSTRAINT PK_DonNhap
	PRIMARY KEY(MaDNhap)
)
CREATE TABLE SP_CN
(
	MaSP INT NOT NULL,
	MaCNhanh INT NOT NULL,
	SoLuongTon INT,
	
	CONSTRAINT PK_SP_CN
	PRIMARY KEY(MaSP,MaCNhanh)
)
CREATE TABLE ChiTietDH
(
	MaSP INT NOT NULL,
	MaDH INT NOT NULL,
	SoLuongSP INT,
	GiaBan INT,
	TenSP NVARCHAR(50),
	ThanhTien INT
	
	CONSTRAINT PK_ChiTietDH
	PRIMARY KEY(MaSP,MaDH)
)
CREATE TABLE QuaTangKem
(
	MaQTang INT NOT NULL IDENTITY,
	TenQT NVARCHAR(50),
	Gia INT,
	
	CONSTRAINT PK_QuaTangKem
	PRIMARY KEY(MaQTang)
)
CREATE TABLE NhaCungCap
(
	MaNCC INT NOT NULL IDENTITY,
	TenNCC NVARCHAR(50),
	DiaChiNCC NVARCHAR(250),
	SDT_NCC VARCHAR(15),
	EmailNCC VARCHAR(30)
	
	CONSTRAINT PK_NhaCungCap
	PRIMARY KEY(MaNCC)
)
CREATE TABLE ChiTietDNhap
(
	MaDNhap INT NOT NULL,
	MaSP INT NOT NULL,
	SoLuong INT,
	GiaNhap INT,
	ThanhTienNH INT
	
	CONSTRAINT PK_ChiTietDNhap
	PRIMARY KEY(MaDNhap,MaSP)
)
CREATE TABLE SanPham
(
	MaSP INT NOT NULL IDENTITY(1,1),
	TenSP NVARCHAR(50),
	ChuDe TINYINT,
	MauSac TINYINT,
	LoaiHoa smallINT,
	MoTa NVARCHAR(MAX),
	TrangThaiHD BIT,
	GiaTruocGiam INT,
	GiaSauGiam INT
	
	CONSTRAINT PK_SanPham
	PRIMARY KEY(MaSP)
)
CREATE TABLE LichSuGia
(
	MaLSGia INT NOT NULL IDENTITY,
	MaSP INT,
	GiaTruocGiam INT,
	GiaSauGiam INT,
	NgayApDung DATETIME
	
	CONSTRAINT PK_LichSuGia
	PRIMARY KEY(MaLSGia)
)
GO

--TẠO RÀNG BUỘC KHÓA NGOẠI
ALTER TABLE LichSuThuong
ADD
	CONSTRAINT FK_LichSuThuong_NhanVien
	FOREIGN KEY(MaNV)
	REFERENCES NhanVien(MaNV)

ALTER TABLE NV_TTinKhac
ADD
	CONSTRAINT FK_NV_TTinKhac_NhanVien
	FOREIGN KEY(MaNV)
	REFERENCES NhanVien(MaNV)

ALTER TABLE LichSuLuong
ADD
	CONSTRAINT FK_LichSuLuong_NhanVien
	FOREIGN KEY(MaNV)
	REFERENCES NhanVien(MaNV)

ALTER TABLE YeuCauHoTro
ADD
	CONSTRAINT FK_YeuCauHoTro_KhachHang FOREIGN KEY(MaKH) REFERENCES KhachHang(MaKH)

ALTER TABLE NVQuanLy 
ADD
	CONSTRAINT FK_NVQuanLy_NhanVien 
		FOREIGN KEY(MaNV) 
		REFERENCES NhanVien(MaNV)

ALTER TABLE NhanVien
ADD
	CONSTRAINT FK_NhanVien_CongViec
		FOREIGN KEY(MaCViec)
		REFERENCES CongViec(MaCViec),
	CONSTRAINT FK_NhanVien_ChiNhanh
		FOREIGN KEY(MaCNhanh)
		REFERENCES ChiNhanh(MaCNhanh)

ALTER TABLE GiaoHang
ADD
	CONSTRAINT FK_GiaoHang_DonHang
		FOREIGN KEY(MaDH)
		REFERENCES DonHang(MaDH),
	CONSTRAINT FK_GiaoHang_NhanVien
		FOREIGN KEY(MaNV)
		REFERENCES NhanVien(MaNV)

ALTER TABLE BanHang
ADD
	CONSTRAINT FK_BanHang_DonHang
		FOREIGN KEY(MaDH)
		REFERENCES DonHang(MaDH),
	CONSTRAINT FK_BanHang_NhanVien
		FOREIGN KEY(MaNV)
		REFERENCES NhanVien(MaNV)

ALTER TABLE KhuVuc
ADD
	CONSTRAINT FK_KhuVuc_ChiNhanh
		FOREIGN KEY(MaCNhanh)
		REFERENCES ChiNhanh(MaCNhanh)

ALTER TABLE DonHang
ADD
	CONSTRAINT FK_DonHang_KhachHang
		FOREIGN KEY(MaKH)
		REFERENCES KhachHang(MaKH),
	CONSTRAINT FK_DonHang_QuaTangKem
		FOREIGN KEY(MaQTang)
		REFERENCES QuaTangKem(MaQTang),
	CONSTRAINT FK_DonHang_ChiNhanh
		FOREIGN KEY(MaCNhanh)
		REFERENCES ChiNhanh(MaCNhanh),
	CONSTRAINT FK_DonHang_KhuVuc
		FOREIGN KEY(MaKV)
		REFERENCES KhuVuc(MaKV)

ALTER TABLE DH_TTinKhac
ADD
	CONSTRAINT FK_DH_TTinKhac_DonHang
		FOREIGN KEY(MaDH)
		REFERENCES DonHang(MaDH)

ALTER TABLE DonNhap
ADD
	CONSTRAINT FK_DonNhap_NhaCungCap
		FOREIGN KEY(MaNCC)
		REFERENCES NhaCungCap(MaNCC),
	CONSTRAINT FK_DonNhap_ChiNhanh
		FOREIGN KEY(MaCNhanh)
		REFERENCES ChiNhanh(MaCNhanh)

ALTER TABLE SP_CN
ADD
	CONSTRAINT FK_SP_CN_SanPham
		FOREIGN KEY(MaSP)
		REFERENCES SanPham(MaSP),
	CONSTRAINT FK_SP_CN_ChiNhanh
		FOREIGN KEY(MaCNhanh)
		REFERENCES ChiNhanh(MaCNhanh)

ALTER TABLE ChiTietDH
ADD
	CONSTRAINT FK_ChiTietDH_SanPham
		FOREIGN KEY(MaSP)
		REFERENCES SanPham(MaSP),
	CONSTRAINT FK_ChiTietDH_DonHang
		FOREIGN KEY(MaDH)
		REFERENCES DonHang(MaDH)

ALTER TABLE ChiTietDNhap
ADD
	CONSTRAINT FK_ChiTietDNhap_DonNhap
		FOREIGN KEY(MaDNhap)
		REFERENCES DonNhap(MaDNhap),
	CONSTRAINT FK_ChiTietDNhap_SanPham
		FOREIGN KEY(MaSP)
		REFERENCES SanPham(MaSP)

ALTER TABLE LichSuGia
ADD
	CONSTRAINT FK_LichSuGia_SanPham
		FOREIGN KEY(MaSP)
		REFERENCES SanPham(MaSP)