
/*
	NOTE QUAN TRỌNG: TRONG MỤC 2/ CỦA PHẦN PARTITION (dòng 50), CÁC BẠN THAY ĐƯỜNG DẪN
	THÀNH ĐƯỜNG DẪN ĐẾN FILE DATA CỦA CÁC BẠN.
		Ví dụ: đường dẫn của mấy bạn như vầy:
				C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\
		Thì thay: "/var/opt/mssql/data/f_hcm.ndf" 
		thành:  C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\f_hcm.ndf
		(Để ý file ở cuối)
*/

USE master
GO
IF DB_ID('QLDH') IS NOT NULL
	DROP DATABASE QLDH
GO
CREATE DATABASE QLDH
GO
USE QLDH
GO

-- PARTITION TABLE CHO THUỘC TÍNH MACN
-- 1/ Tạo File groups
ALTER DATABASE QLDH
	ADD FILEGROUP FG_ChiNhanh_HCM
GO
ALTER DATABASE QLDH
	ADD FILEGROUP FG_ChiNhanh_HN
GO
ALTER DATABASE QLDH
	ADD FILEGROUP FG_ChiNhanh_CN1
GO
ALTER DATABASE QLDH
	ADD FILEGROUP FG_ChiNhanh_CN2
GO
ALTER DATABASE QLDH
	ADD FILEGROUP FG_ChiNhanh_CN3
GO
ALTER DATABASE QLDH
	ADD FILEGROUP FG_ChiNhanh_CN4
GO
ALTER DATABASE QLDH
	ADD FILEGROUP FG_ChiNhanh_CN5
GO
ALTER DATABASE QLDH
	ADD FILEGROUP FG_ChiNhanh_CN6
GO
ALTER DATABASE QLDH
	ADD FILEGROUP FG_ChiNhanh_CN7
GO

-- 2/ Tạo files
ALTER DATABASE QLDH
ADD FILE 
(
	NAME = f_hcm,
	FILENAME = '/var/opt/mssql/data/f_hcm.ndf',
	SIZE = 5MB,
	MAXSIZE = 1000MB,
	FILEGROWTH = 5MB
)
TO FILEGROUP FG_ChiNhanh_HCM
GO
ALTER DATABASE QLDH
ADD FILE 
(
	NAME = f_hn,
	FILENAME = '/var/opt/mssql/data/f_hn.ndf',
	SIZE = 5MB,
	MAXSIZE = 1000MB,
	FILEGROWTH = 5MB
)
TO FILEGROUP FG_ChiNhanh_HN
GO
ALTER DATABASE QLDH
ADD FILE 
(
	NAME = f_cn1,
	FILENAME = '/var/opt/mssql/data/f_cn1.ndf',
	SIZE = 5MB,
	MAXSIZE = 1000MB,
	FILEGROWTH = 5MB
)
TO FILEGROUP FG_ChiNhanh_CN1	
GO
ALTER DATABASE QLDH
ADD FILE 
(
	NAME = f_cn2,
	FILENAME = '/var/opt/mssql/data/f_cn2.ndf',
	SIZE = 5MB,
	MAXSIZE = 1000MB,
	FILEGROWTH = 5MB
)
TO FILEGROUP FG_ChiNhanh_CN2
GO
ALTER DATABASE QLDH
ADD FILE 
(
	NAME = f_cn3,
	FILENAME = '/var/opt/mssql/data/f_cn3.ndf',
	SIZE = 5MB,
	MAXSIZE = 1000MB,
	FILEGROWTH = 5MB
)
TO FILEGROUP FG_ChiNhanh_CN3
GO
ALTER DATABASE QLDH
ADD FILE 
(
	NAME = f_cn4,
	FILENAME = '/var/opt/mssql/data/f_cn4.ndf',
	SIZE = 5MB,
	MAXSIZE = 1000MB,
	FILEGROWTH = 5MB
)
TO FILEGROUP FG_ChiNhanh_CN4
GO
ALTER DATABASE QLDH
ADD FILE 
(
	NAME = f_cn5,
	FILENAME = '/var/opt/mssql/data/f_cn5.ndf',
	SIZE = 5MB,
	MAXSIZE = 1000MB,
	FILEGROWTH = 5MB
)
TO FILEGROUP FG_ChiNhanh_CN5
GO
ALTER DATABASE QLDH
ADD FILE 
(
	NAME = f_cn6,
	FILENAME = '/var/opt/mssql/data/f_cn6.ndf',
	SIZE = 5MB,
	MAXSIZE = 1000MB,
	FILEGROWTH = 5MB
)
TO FILEGROUP FG_ChiNhanh_CN6
GO
ALTER DATABASE QLDH
ADD FILE 
(
	NAME = f_cn7,
	FILENAME = '/var/opt/mssql/data/f_cn7.ndf',
	SIZE = 5MB,
	MAXSIZE = 1000MB,
	FILEGROWTH = 5MB
)
TO FILEGROUP FG_ChiNhanh_CN7
GO

-- 3/ Tạo partition function
CREATE PARTITION FUNCTION pfunc_ChiNhanh (INT)
	AS RANGE LEFT FOR VALUES (6, 10, 45, 80, 115, 150, 185, 220);
GO

-- 4/ Tạo partition scheme
CREATE PARTITION SCHEME psche_ChiNhanh 
	AS PARTITION pfunc_ChiNhanh
	TO 
	(
		FG_ChiNhanh_HCM, FG_ChiNhanh_HN, FG_ChiNhanh_CN1,
		FG_ChiNhanh_CN2, FG_ChiNhanh_CN3, FG_ChiNhanh_CN4,
		FG_ChiNhanh_CN5, FG_ChiNhanh_CN6, FG_ChiNhanh_CN7
	)
GO



-- TẠO BẢNG VÀ RÀNG BUỘC KHÓA CHÍNH
CREATE TABLE CongViec
(
	MaCViec INT NOT NULL IDENTITY,
	TenCViec NVARCHAR(50) NOT NULL CHECK (TenCViec <> ' ')
	
	CONSTRAINT PK_CongViec 
	PRIMARY KEY (MaCViec)
)
GO
CREATE TABLE LichSuThuong
(
	MaLSThuong INT NOT NULL IDENTITY,
	TienThuong INT NOT NULL,
	NgayThuong DATE NOT NULL,
	MaNV INT NOT NULL,
	LyDo NVARCHAR(500)
	
	CONSTRAINT PK_LichSuThuong 
	PRIMARY KEY (MaLSThuong)
)
GO
CREATE TABLE NV_TTinKhac
(
	MaNV INT NOT NULL,
	CMND_NV CHAR(12),
	SDT_NV CHAR(10),
	NgaySinhNV DATE,
	DiaChiNV NVARCHAR(255)
	
	CONSTRAINT PK_NV_TTinKhac 
	PRIMARY KEY (MaNV)
)
GO
CREATE TABLE LichSuLuong
(
	MaLSLuong INT NOT NULL IDENTITY,
	MaNV INT NOT NULL,
	NgayBD DATE NOT NULL,
	Luong INT NOT NULL,
	
	CONSTRAINT PK_LichSuLuong
	PRIMARY KEY (MaLSLuong)
)
GO
CREATE TABLE YeuCauHoTro
(
	MaYC INT NOT NULL IDENTITY,
	MaKH INT,
	Noidung NVARCHAR(MAX),
	TrangThaiYCau TINYINT NOT NULL
	
	CONSTRAINT PK_YeuCauHoTro
	PRIMARY KEY (MaYC)
)
GO
CREATE TABLE NVQuanLy
(
	MaNV INT NOT NULL,
	MatKhauQL VARCHAR(20) CHECK (MatKhauQL <> ' ')
	
	CONSTRAINT PK_NVQuanLy
	PRIMARY KEY (MaNV)
)
GO
CREATE TABLE NhanVien
(
	MaNV INT IDENTITY,
	HoTenNV NVARCHAR(50) CHECK (HoTenNV <> ' '),
	LuongHienTai INT NOT NULL,
	TrangThaiHD BIT NOT NULL,
	TenCViec NVARCHAR(50) CHECK (TenCViec <> ' '),
	MaCViec INT NOT NULL,
	MaCNhanh INT NOT NULL,
	
	CONSTRAINT PK_NhanVien
	PRIMARY KEY (MaNV)
)
GO
CREATE TABLE GiaoHang
(
	MaDH INT,
	MaNV INT NOT NULL,
	NgayGiao DATETIME
	
	CONSTRAINT PK_GiaoHang
	PRIMARY KEY (MaDH)
)
GO
CREATE TABLE BanHang
(
	MaDH INT NOT NULL,
	MaNV INT NOT NULL,
	
	CONSTRAINT PK_BanHang
	PRIMARY KEY (MaDH)
)
GO
CREATE TABLE KhachHang
(
	MaKH INT IDENTITY,
	HoKH NVARCHAR(30) CHECK (HoKH <> ' '),
	TenKH NVARCHAR(30) CHECK (TenKH <> ' '),
	SDT_KH VARCHAR(15),
	EmailKH VARCHAR(30) CHECK (EmailKH <> ' ') UNIQUE,
	MatKhauKH VARCHAR(20) CHECK (MatKhauKH <> ''),
	DiaChiKH NVARCHAR(255),
	
	CONSTRAINT PK_KhachHang
	PRIMARY KEY (MaKH)
)
GO
CREATE TABLE ChiNhanh
(
	MaCNhanh INT IDENTITY,
	TenCNhanh NVARCHAR(50) CHECK (TenCNhanh <> ' '),
	DiaChiCNhanh NVARCHAR(255) CHECK (DiaChiCNhanh <> ' '),
	SDT_CNhanh CHAR(15),
	PasswordBH VARCHAR(20) CHECK (PasswordBH <> ' '),
	TrangThaiHD BIT NOT NULL,
	MaTinh TINYINT NOT NULL,
	TenTinh NVARCHAR(30),

	CONSTRAINT PK_ChiNhanh
	PRIMARY KEY (MaCNhanh)
)
GO
CREATE TABLE KhuVuc
(
	MaKV INT IDENTITY,
	MaTinh TINYINT NOT NULL,
	TenTinh NVARCHAR(30) CHECK (TenTinh <> ' '),
	Ten_QHuyen NVARCHAR(30) CHECK (Ten_QHuyen <> ' '),
	PhiGiaoHang INT NOT NULL,
	MaCNhanh INT NOT NULL
	
	CONSTRAINT PK_KhuVuc
	PRIMARY KEY (MaKV)
)
GO
CREATE TABLE DonHang
(
	MaDH INT NOT NULL IDENTITY,
	SDT_NgNhan CHAR(10),
	NgayLap DATETIME NOT NULL,
	HinhThucTT TINYINT NOT NULL,
	TrangThaiDH TINYINT NOT NULL,
	TongTienSP INT NOT NULL,
	PhiGiaoHang INT NOT NULL,
	TongTienDH INT NOT NULL,
	MaKH INT,
	MaQTang INT,
	MaCNhanh INT NOT NULL,
	MaKV INT NOT NULL
	
	CONSTRAINT PK_DonHang
	PRIMARY KEY NONCLUSTERED (MaDH)	
)
GO

CREATE CLUSTERED INDEX inx_DonHang_MaCNhanh 
	ON DonHang (MaDH, MaCNhanh) 
	ON psche_ChiNhanh (MaCNhanh)
GO

CREATE TABLE DH_TTinKhac
(
	MaDH INT,
	Email_NgGui VARCHAR(30),
	DiaChi_NgGui NVARCHAR(255),
	SDT_NgGui CHAR(10),
	
	CONSTRAINT PK_DH_TTinKhac
	PRIMARY KEY (MaDH)
)
GO
CREATE TABLE DonNhap
(
	MaDNhap INT IDENTITY,
	TongTienNhap INT NOT NULL,
	NgayNhanHang DATE NOT NULL,
	MaNCC INT NOT NULL,
	MaCNhanh INT NOT NULL
	
	CONSTRAINT PK_DonNhap
	PRIMARY KEY (MaDNhap)
)
GO
CREATE TABLE SP_CN
(
	MaSP INT,
	MaCNhanh INT NOT NULL,
	SoLuongTon INT NOT NULL,
	
	CONSTRAINT PK_SP_CN
	PRIMARY KEY (MaCNhanh, MaSP)
)
GO
CREATE TABLE ChiTietDH
(
	MaSP INT,
	MaDH INT,
	SoLuongSP INT NOT NULL,
	GiaBan INT NOT NULL,
	TenSP NVARCHAR(50),
	ThanhTien INT NOT NULL
	
	CONSTRAINT PK_ChiTietDH
	PRIMARY KEY (MaDH, MaSP)
)
GO
CREATE TABLE QuaTangKem
(
	MaQTang INT IDENTITY,
	TenQT NVARCHAR(50) CHECK (TenQT <> ' '),
	Gia INT NOT NULL,
	
	CONSTRAINT PK_QuaTangKem
	PRIMARY KEY (MaQTang)
)
GO
CREATE TABLE NhaCungCap
(
	MaNCC INT IDENTITY,
	TenNCC NVARCHAR(50),
	DiaChiNCC NVARCHAR(255),
	SDT_NCC VARCHAR(15),
	EmailNCC VARCHAR(30)
	
	CONSTRAINT PK_NhaCungCap
	PRIMARY KEY (MaNCC)
)
GO
CREATE TABLE ChiTietDNhap
(
	MaDNhap INT,
	MaSP INT NOT NULL,
	SoLuong INT NOT NULL,
	GiaNhap INT NOT NULL,
	ThanhTienNH INT NOT NULL
	
	CONSTRAINT PK_ChiTietDNhap
	PRIMARY KEY (MaDNhap, MaSP)
)
GO
CREATE TABLE SanPham
(
	MaSP INT IDENTITY,
	TenSP NVARCHAR(50) CHECK (TenSP <> ' '),
	MaMau TINYINT NOT NULL,
	MaLoaiHoa SMAllINT NOT NULL,
	TenLoaiHoa NVARCHAR(30),
	MoTa NVARCHAR(1500),
	TrangThaiHD BIT NOT NULL,
	GiaTruocGiam INT NOT NULL,
	GiaSauGiam INT NOT NULL
	
	CONSTRAINT PK_SanPham
	PRIMARY KEY (MaSP)
)
GO
CREATE TABLE Mau
(
	MaMau TINYINT IDENTITY,
	TenMau NVARCHAR(20) CHECK (TenMau <> ' '),

	CONSTRAINT PK_Mau 
	PRIMARY KEY (MaMau)
)
GO
CREATE TABLE LoaiHoa
(
	MaLoaiHoa SMAllINT IDENTITY,
	TenLoaiHoa NVARCHAR(30) CHECK (TenLoaiHoa <> ' '),

	CONSTRAINT PK_LoaiHoa
	PRIMARY KEY (MaLoaiHoa)
)
GO
CREATE TABLE SP_CD
(
	MaSP INT,
	MaCDe TINYINT,
	ChuDe NVARCHAR(50) CHECK (ChuDe <> ' '),

	CONSTRAINT PK_SP_CD
	PRIMARY KEY (MaSP, MaCDe)
)
GO
CREATE TABLE ChuDe
(
	MaCDe TINYINT IDENTITY,
	ChuDe NVARCHAR(50) CHECK (ChuDe <> ' '),

	CONSTRAINT PK_ChuDe
	PRIMARY KEY (MaCDe)
)
GO
CREATE TABLE LichSuGia
(
	MaLSGia INT IDENTITY,
	MaSP INT NOT NULL,
	GiaTruocGiam INT NOT NULL,
	GiaSauGiam INT NOT NULL,
	NgayApDung DATETIME NOT NULL
	
	CONSTRAINT PK_LichSuGia
	PRIMARY KEY (MaLSGia)
)
GO



-- TẠO RÀNG BUỘC KHÓA NGOẠI
ALTER TABLE LichSuThuong
ADD
	CONSTRAINT FK_LichSuThuong_NhanVien
		FOREIGN KEY (MaNV)
		REFERENCES NhanVien (MaNV)

ALTER TABLE NV_TTinKhac
ADD
	CONSTRAINT FK_NV_TTinKhac_NhanVien
		FOREIGN KEY (MaNV)
		REFERENCES NhanVien (MaNV)

ALTER TABLE LichSuLuong
ADD
	CONSTRAINT FK_LichSuLuong_NhanVien 
		FOREIGN KEY (MaNV) 
		REFERENCES NhanVien (MaNV)

ALTER TABLE YeuCauHoTro
ADD
	CONSTRAINT FK_YeuCauHoTro_KhachHang 
		FOREIGN KEY (MaKH) 
		REFERENCES KhachHang (MaKH)

ALTER TABLE NVQuanLy 
ADD
	CONSTRAINT FK_NVQuanLy_NhanVien 
		FOREIGN KEY (MaNV) 
		REFERENCES NhanVien (MaNV)

ALTER TABLE NhanVien
ADD
	CONSTRAINT FK_NhanVien_CongViec
		FOREIGN KEY (MaCViec)
		REFERENCES CongViec (MaCViec),
	CONSTRAINT FK_NhanVien_ChiNhanh
		FOREIGN KEY (MaCNhanh)
		REFERENCES ChiNhanh (MaCNhanh)

ALTER TABLE GiaoHang
ADD
	CONSTRAINT FK_GiaoHang_DonHang
		FOREIGN KEY (MaDH)
		REFERENCES DonHang (MaDH),
	CONSTRAINT FK_GiaoHang_NhanVien
		FOREIGN KEY (MaNV)
		REFERENCES NhanVien (MaNV)

ALTER TABLE BanHang
ADD
	CONSTRAINT FK_BanHang_DonHang
		FOREIGN KEY (MaDH)
		REFERENCES DonHang (MaDH),
	CONSTRAINT FK_BanHang_NhanVien
		FOREIGN KEY (MaNV)
		REFERENCES NhanVien (MaNV)

ALTER TABLE KhuVuc
ADD
	CONSTRAINT FK_KhuVuc_ChiNhanh
		FOREIGN KEY (MaCNhanh)
		REFERENCES ChiNhanh (MaCNhanh)

ALTER TABLE DonHang
ADD
	CONSTRAINT FK_DonHang_KhachHang
		FOREIGN KEY (MaKH)
		REFERENCES KhachHang (MaKH),
	CONSTRAINT FK_DonHang_QuaTangKem
		FOREIGN KEY (MaQTang)
		REFERENCES QuaTangKem (MaQTang),
	CONSTRAINT FK_DonHang_ChiNhanh
		FOREIGN KEY (MaCNhanh)
		REFERENCES ChiNhanh (MaCNhanh),
	CONSTRAINT FK_DonHang_KhuVuc
		FOREIGN KEY (MaKV)
		REFERENCES KhuVuc (MaKV)

ALTER TABLE DH_TTinKhac
ADD
	CONSTRAINT FK_DH_TTinKhac_DonHang
		FOREIGN KEY (MaDH)
		REFERENCES DonHang (MaDH)

ALTER TABLE DonNhap
ADD
	CONSTRAINT FK_DonNhap_NhaCungCap
		FOREIGN KEY (MaNCC)
		REFERENCES NhaCungCap (MaNCC),
	CONSTRAINT FK_DonNhap_ChiNhanh
		FOREIGN KEY (MaCNhanh)
		REFERENCES ChiNhanh (MaCNhanh)

ALTER TABLE SP_CN
ADD
	CONSTRAINT FK_SP_CN_SanPham
		FOREIGN KEY (MaSP)
		REFERENCES SanPham (MaSP),
	CONSTRAINT FK_SP_CN_ChiNhanh
		FOREIGN KEY (MaCNhanh)
		REFERENCES ChiNhanh (MaCNhanh)

ALTER TABLE ChiTietDH
ADD
	CONSTRAINT FK_ChiTietDH_SanPham
		FOREIGN KEY (MaSP)
		REFERENCES SanPham (MaSP),
	CONSTRAINT FK_ChiTietDH_DonHang
		FOREIGN KEY (MaDH)
		REFERENCES DonHang (MaDH)

ALTER TABLE ChiTietDNhap
ADD
	CONSTRAINT FK_ChiTietDNhap_DonNhap
		FOREIGN KEY (MaDNhap)
		REFERENCES DonNhap(MaDNhap),
	CONSTRAINT FK_ChiTietDNhap_SanPham
		FOREIGN KEY (MaSP)
		REFERENCES SanPham (MaSP)

ALTER TABLE LichSuGia
ADD
	CONSTRAINT FK_LichSuGia_SanPham
		FOREIGN KEY (MaSP)
		REFERENCES SanPham (MaSP)

ALTER TABLE SanPham
ADD
	CONSTRAINT FK_SanPham_Mau
		FOREIGN KEY (MaMau)
		REFERENCES Mau (MaMau),
	CONSTRAINT FK_SanPham_LoaiHoa
		FOREIGN KEY (MaLoaiHoa)
		REFERENCES LoaiHoa (MaLoaiHoa)
GO